config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"

Rails.application.routes.draw do
  namespace :administrator do
      resources :admins
      resources :users
      resources :patients
      resources :enqueues

      root to: "admins#index"
  end

  devise_scope :admin do
    authenticated :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end

  root to: "enqueues#index"

  devise_for :admins, path: "admin", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  scope "/#{I18n.t("routes.patient_enqueues")}/:invite_token", as: :patients do
    resources :appointments, path: "", only: [:new, :create]
  end

  resource :invite_link, only: [:show]

  resources :enqueues, as: "appointments", only: [:index, :update, :destroy], path: I18n.t("routes.enqueues")
  resources :patients, only: [:show], path: I18n.t("routes.patients")
end

app/views/partials/_flash.html.haml
- if flash.any?
  .flash.container
    - flash.each do |key, message|
      - type = ApplicationHelper::FLASHES[key]
      .alert.alert-dismissible.d-flex.align-items-centerfade.show{ class: "alert-#{type}", role: "alert" }
        %p.mb-0= message
        = button_tag "", type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close"

app/views/partials/_sidebar.html.haml
%aside.sidebar.flex-shrink-9.bg-light.shadow.p-1
  = link_to root_path, class: "sidebar-item" do
    %i.bi.bi-house-fill
  - if current_user.present?
    = link_to edit_user_registration_path, class: "sidebar-item" do
      %i.bi.bi-person-circle
    = link_to invite_link_path, class: "sidebar-item" do
      %i.bi.bi-link
    = link_to destroy_user_session_path, method: :delete, class: "sidebar-item bg-light sidebar-end-item" do
      %i.bi.bi-box-arrow-in-right