config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"

Rails.application.routes.draw do
  namespace :administrator do
      resources :admins
      resources :users
      resources :patients
      resources :enqueues

      root to: "admins#index"
  end

  devise_scope :admin do
    authenticated :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end

  root to: "enqueues#index"

  devise_for :admins, path: "admin", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  scope "/#{I18n.t("routes.patient_enqueues")}/:invite_token", as: :patients do
    resources :appointments, path: "", only: [:new, :create]
  end

  resource :invite_link, only: [:show]

  resources :enqueues, as: "appointments", only: [:index, :update, :destroy], path: I18n.t("routes.enqueues")
  resources :patients, only: [:show], path: I18n.t("routes.patients")
end

app/models/enqueue.rb
# frozen_string_literal: true

class Enqueue < ApplicationRecord
  TABLE_HEADERS = %w(patient_name patient_phone patient_email shift due_date).freeze

  belongs_to :user, inverse_of: :enqueues
  belongs_to :patient, inverse_of: :enqueue, dependent: :destroy

  scope :booked, -> { where.not(booked_at: nil) }
  scope :pending, -> { where(booked_at: nil) }

  def next_notification_date
    return nil if booked_at.present?

    updated_at + user.notification_days.days
  end

  def due?
    return false if next_notification_date.nil?

    Time.current > next_notification_date
  end

  def book!
    self.booked_at = Time.current
    save!(touch: false)
  end

  def unbook!
    self.booked_at = nil
    save!(touch: false)
  end

  def snooze!
    touch(:updated_at)
  end
end

app/controllers/administrator/enqueues_controller.rb
# frozen_string_literal: true

module Administrator
  class EnqueuesController < Administrator::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/enqueues_controller.rb
# frozen_string_literal: true

class EnqueuesController < ApplicationController
  before_action :authenticate_user!

  def index
    appointments = current_user.enqueues.includes(:patient)
    @booked = appointments.booked
    @pending = appointments - @booked
  end

  def update
    enqueue = current_user.enqueues.find(enqueue_id)

    flash[:success] = t(".snoozed") if snooze? && enqueue.snooze!
    flash[:success] = t(".booked") if book? && enqueue.book!
    flash[:success] = t(".unbooked") if unbook? && enqueue.unbook!

    flash[:error] = t(".error") if flash[:success].nil?

    redirect_to(appointments_path)
  end

  def destroy
    if current_user.enqueues.find_by(id: enqueue_id).try(:destroy)
      flash[:success] = t(".success")
    else
      flash[:error] = t(".error")
    end

    redirect_to(appointments_path)
  end

  private

    def enqueue_id
      params[:id]
    end

    def snooze?
      params[:snooze].present?
    end

    def book?
      params[:book].present?
    end

    def unbook?
      params[:unbook].present?
    end
end

app/views/enqueues/index.html.haml
%h1= t(".title")

- if @pending.any?
  .table-responsive
    %table.table.table-hover
      %thead
        %th{ scope: "col" } #
        - Enqueue::TABLE_HEADERS.each do |header|
          %th{ scope: "col" }= t(".table.headers.#{header}")
        %th{ scope: "col" }= t(".table.headers.actions")
      %tbody
        - @pending.each do |appointment|
          %tr{ scope: "row", class: (appointment.due? ? "table-danger" : "")}
            %td= appointment.id
            %td= appointment.patient.name
            %td= appointment.patient.phone
            %td= appointment.patient.email
            %td= t("activerecord.attributes.patient.shifts.#{appointment.patient.shift}")
            %td= appointment.booked_at.nil? ? l(appointment.next_notification_date, format: :compact) : ""
            %td
              - if appointment.due?
                = form_with(url: appointment_path(appointment), method: "PUT", class: "d-inline-block") do |f|
                  = f.hidden_field(:snooze, value: true)
                  = button_tag(type: "submit",
                      class: "btn btn-warning shake me-3",
                      "data-bs-toggle": "tooltip",
                      "data-bs-placement": "bottom",
                      title: t(".table.actions.snooze")) do
                    %i.bi.bi-alarm-fill
              - if appointment.booked_at.nil?
                = form_with(url: appointment_path(appointment), method: "PUT", class: "d-inline-block") do |f|
                  = f.hidden_field(:book, value: true)
                  = button_tag(type: "submit",
                      class: "btn btn-success me-3",
                      "data-bs-toggle": "tooltip",
                      "data-bs-placement": "bottom",
                      title: t(".table.actions.book")) do
                    %i.bi.bi-calendar-check-fill
              = link_to(appointment.patient,
                  class: "btn btn-primary me-3",
                  "data-bs-toggle": "tooltip",
                  "data-bs-placement": "bottom",
                  title: t(".table.actions.patient")) do
                %i.bi.bi-person-lines-fill
- else
  %h2.text-center.my-5= t(".no_pending")

- if @booked.any?
  %hr
  %h2= t(".booked_title")
  .table-responsive
    %table.table.table-striped.table-hover
      %thead
        %th{ scope: "col" } #
        - (Enqueue::TABLE_HEADERS - %w(shift due_date)).each do |header|
          %th{ scope: "col" }= t(".table.headers.#{header}")
        %th{ scope: "col" }= t(".table.headers.booked_at_date")
        %th{ scope: "col" }= t(".table.headers.actions")
      %tbody
        - @booked.each do |appointment|
          %tr{ scope: "row"}
            %td= appointment.id
            %td= appointment.patient.name
            %td= appointment.patient.phone
            %td= appointment.patient.email
            %td= l(appointment.booked_at, format: :compact)
            %td
              = form_with(url: appointment_path(appointment), method: "PUT", class: "d-inline-block") do |f|
                = f.hidden_field(:unbook, value: true)
                = button_tag(type: "submit",
                    class: "btn btn-info me-3",
                    "data-bs-toggle": "tooltip",
                    "data-bs-placement": "bottom",
                    title: t(".table.actions.unbook")) do
                  %i.bi.bi-calendar-x-fill
              = link_to(appointment.patient,
                  class: "btn btn-primary me-3",
                  "data-bs-toggle": "tooltip",
                  "data-bs-placement": "bottom",
                  title: t(".table.actions.patient")) do
                %i.bi.bi-person-lines-fill
              = link_to(appointment_path(appointment),
                  method: "DELETE",
                  type: "button",
                  class: "btn btn-danger",
                  "data-bs-toggle": "tooltip",
                  "data-bs-placement": "bottom",
                  title: t(".table.actions.delete")) do
                %i.bi.bi-person-x-fill