config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"

Rails.application.routes.draw do
  namespace :administrator do
      resources :admins
      resources :users
      resources :patients
      resources :enqueues

      root to: "admins#index"
  end

  devise_scope :admin do
    authenticated :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end

  root to: "enqueues#index"

  devise_for :admins, path: "admin", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  scope "/#{I18n.t("routes.patient_enqueues")}/:invite_token", as: :patients do
    resources :appointments, path: "", only: [:new, :create]
  end

  resource :invite_link, only: [:show]

  resources :enqueues, as: "appointments", only: [:index, :update, :destroy], path: I18n.t("routes.enqueues")
  resources :patients, only: [:show], path: I18n.t("routes.patients")
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  layout "public"
  before_action :set_user!
  before_action :set_token!

  def new
    @patient = @user.patients.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save && enqueue = @user.enqueues.create(patient: @patient)
      EnqueueMailer.new_patient_email(enqueue).deliver_later
      render "thanks"
    else
      flash[:error] = @patient.errors.full_messages.join("\n")
      redirect_to new_patients_appointment_path(invite_token: invite_token)
    end
  end

  private

    def invite_token
      params[:invite_token]
    end

    def set_user!
      @user = User.find_by!(invite_token: invite_token)
    end

    def set_token!
      @invite_token = invite_token
    end

    def patient_params
      params.require(:patient).permit(
        :name, :email, :phone, :shift
      )
    end
end

app/views/appointments/new.html.haml
%p= t(".instructions_html", name: @user.name)
= form_for(@patient, url: patients_appointments_path(invite_token: @invite_token), builder: BootstrapBuilder) do |f|
  .field
    = f.label :name
    = f.text_field :name, required: true
  .field
    = f.label :phone
    = f.telephone_field :phone, required: true, placeholder: "XXX-XXX-XXXX"
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :shift
    = f.select(:shift, options_for_select(shifts_options), required: true, class: "form-select")
  .actions.text-center.mt-4.mt-md-5
    = f.submit t("appointments.new_appointment"), class: "btn btn-primary btn-lg"

app/views/appointments/thanks.html.haml
%h1.text-center= t(".success")